import Container from "@/components/layouts/container";
import "./globals.css";
import type { Metadata } from "next";
import Header from "@/components/layouts/header";
import Footer from "@/components/layouts/footer";
import Sidebar from "@/components/layouts/sidebar";
import ChatProvider from "./ChatProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <ChatProvider>
          <Container>
            <Header>ヘッダです</Header>
            <Sidebar>サイドバーです</Sidebar>
            <main>{children}</main>
            <Footer />
          </Container>
        </ChatProvider>
      </body>
    </html>
  );
}
